# Generated by Django 5.0.1 on 2024-01-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=100)),
                ('annee_publication', models.IntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('categorie', models.CharField(max_length=100)),
                ('disponibilite', models.BooleanField(default=True)),
                ('nombre_exemplaires', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='mybag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=200, unique=True)),
                ('reader_name', models.CharField(max_length=200)),
                ('reader_contact', models.CharField(max_length=200)),
                ('reader_start_date_time', models.TextField()),
                ('reader_return_date_time', models.TextField()),
            ],
        ),
    ]
