# Generated by Django 5.0.1 on 2024-02-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0004_remove_cartitem_cart_remove_cartitem_book_mybag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybagitem',
            name='mybag',
        ),
        migrations.RemoveField(
            model_name='mybagitem',
            name='book',
        ),
        migrations.AddField(
            model_name='reader',
            name='mybag',
            field=models.ManyToManyField(blank=True, related_name='readers', to='lims_app.book'),
        ),
        migrations.DeleteModel(
            name='MyBag',
        ),
        migrations.DeleteModel(
            name='MyBagItem',
        ),
    ]
